website:
  title: "Lily Zhang"
  description: "PhD in Biochemistry and Molecular Biology | Data Enthusiast" 
  image: "img/my_image.png"
  favicon: img/peach.png
  
  navbar:
    pinned: true
    logo: /img/peach.png
    
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    right:
      - icon: facebook
        href: https://www.facebook.com/lily.zhang.167284
      - icon: linkedin
        href: https://www.linkedin.com/in/lily-zhang-29b78b257/
      - icon: envelope
        aria-label: email
        href: "mailto: shitao.zhang@case.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
#  page-footer: 
#    left: |
#      <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
#    center: |
#      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
#    right: |
#      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true